namespace PecTec.Riot.LoL.Models.Items
{
    public class Stats
    {
        public decimal FlatHPPoolMod { get; set; }
        public decimal RFlatHPModPerLevel { get; set; }
        public decimal FlatMPPoolMod { get; set; }
        public decimal RFlatMPModPerLevel { get; set; }
        public decimal PercentHPPoolMod { get; set; }
        public decimal PercentMPPoolMod { get; set; }
        public decimal FlatHPRegenMod { get; set; }
        public decimal RFlatHPRegenModPerLevel { get; set; }
        public decimal PercentHPRegenMod { get; set; }
        public decimal FlatMPRegenMod { get; set; }
        public decimal RFlatMPRegenModPerLevel { get; set; }
        public decimal PercentMPRegenMod { get; set; }
        public decimal FlatArmorMod { get; set; }
        public decimal RFlatArmorModPerLevel { get; set; }
        public decimal PercentArmorMod { get; set; }
        public decimal RFlatArmorPenetrationMod { get; set; }
        public decimal RFlatArmorPenetrationModPerLevel { get; set; }
        public decimal RPercentArmorPenetrationMod { get; set; }
        public decimal RPercentArmorPenetrationModPerLevel { get; set; }
        public decimal FlatPhysicalDamageMod { get; set; }
        public decimal RFlatPhysicalDamageModPerLevel { get; set; }
        public decimal PercentPhysicalDamageMod { get; set; }
        public decimal FlatMagicDamageMod { get; set; }
        public decimal RFlatMagicDamageModPerLevel { get; set; }
        public decimal PercentMagicDamageMod { get; set; }
        public decimal FlatMovementSpeedMod { get; set; }
        public decimal RFlatMovementSpeedModPerLevel { get; set; }
        public decimal PercentMovementSpeedMod { get; set; }
        public decimal RPercentMovementSpeedModPerLevel { get; set; }
        public decimal FlatAttackSpeedMod { get; set; }
        public decimal PercentAttackSpeedMod { get; set; }
        public decimal RPercentAttackSpeedModPerLevel { get; set; }
        public decimal RFlatDodgeMod { get; set; }
        public decimal RFlatDodgeModPerLevel { get; set; }
        public decimal PercentDodgeMod { get; set; }
        public decimal FlatCritChanceMod { get; set; }
        public decimal RFlatCritChanceModPerLevel { get; set; }
        public decimal PercentCritChanceMod { get; set; }
        public decimal FlatCritDamageMod { get; set; }
        public decimal RFlatCritDamageModPerLevel { get; set; }
        public decimal PercentCritDamageMod { get; set; }
        public decimal FlatBlockMod { get; set; }
        public decimal PercentBlockMod { get; set; }
        public decimal FlatSpellBlockMod { get; set; }
        public decimal RFlatSpellBlockModPerLevel { get; set; }
        public decimal PercentSpellBlockMod { get; set; }
        public decimal FlatEXPBonus { get; set; }
        public decimal PercentEXPBonus { get; set; }
        public decimal RPercentCooldownMod { get; set; }
        public decimal RPercentCooldownModPerLevel { get; set; }
        public decimal RFlatTimeDeadMod { get; set; }
        public decimal RFlatTimeDeadModPerLevel { get; set; }
        public decimal RPercentTimeDeadMod { get; set; }
        public decimal RPercentTimeDeadModPerLevel { get; set; }
        public decimal RFlatGoldPer10Mod { get; set; }
        public decimal RFlatMagicPenetrationMod { get; set; }
        public decimal RFlatMagicPenetrationModPerLevel { get; set; }
        public decimal RPercentMagicPenetrationMod { get; set; }
        public decimal RPercentMagicPenetrationModPerLevel { get; set; }
        public decimal FlatEnergyRegenMod { get; set; }
        public decimal RFlatEnergyRegenModPerLevel { get; set; }
        public decimal FlatEnergyPoolMod { get; set; }
        public decimal RFlatEnergyModPerLevel { get; set; }
        public decimal PercentLifeStealMod { get; set; }
        public decimal PercentSpellVampMod { get; set; }
    }
}
